import React, { useState } from 'react';
import { WeeklyMealPlan, UserProfile } from '../types';
import {
  X, Calendar, Clock, CheckCircle2, Sparkles, Send, Copy,
  Check, Share2, ChefHat, Layers, ShieldCheck, Flame, Droplet,
  Download, Printer
} from 'lucide-react';
import { motion } from 'motion/react';

interface BatchPrepGuideModalProps {
  isOpen?: boolean;
  plan?: WeeklyMealPlan;
  userProfile?: UserProfile;
  onClose: () => void;
}

export const BatchPrepGuideModal: React.FC<BatchPrepGuideModalProps> = ({
  isOpen = true,
  plan,
  userProfile,
  onClose,
}) => {
  if (!isOpen) return null;

  const [copyToast, setCopyToast] = useState(false);
  const [checkedTasks, setCheckedTasks] = useState<Record<string, boolean>>({});

  // Dynamic analysis of ingredients from the plan
  const allIngredients = React.useMemo(() => {
    const set = new Set<string>();
    if (plan?.days) {
      plan.days.forEach((d) => {
        [d.breakfast, d.lunch, d.eveningSnack, d.dinner].forEach((m) => {
          if (m?.ingredients) {
            m.ingredients.forEach((i) => set.add(i.toLowerCase()));
          }
        });
      });
    }
    return Array.from(set);
  }, [plan]);

  const hasChana = allIngredients.some((i) => i.includes('chana') || i.includes('chickpea') || i.includes('cholay'));
  const hasRajma = allIngredients.some((i) => i.includes('rajma') || i.includes('kidney'));
  const hasMoong = allIngredients.some((i) => i.includes('moong') || i.includes('sprout'));
  const hasPaneer = allIngredients.some((i) => i.includes('paneer') || i.includes('tofu'));
  const hasOats = allIngredients.some((i) => i.includes('oats') || i.includes('chia'));
  const hasBesan = allIngredients.some((i) => i.includes('besan') || i.includes('gram flour') || i.includes('chilla'));

  const toggleTask = (key: string) => {
    setCheckedTasks((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const generatePrepText = () => {
    let text = `🥘 *DietPlan AI — Sunday Batch Meal Prep & Kitchen Roadmap*\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `👤 *Member:* ${userProfile?.name || 'User'} | 📅 *Plan:* ${plan?.planTitle || '7-Day Plan'}\n`;
    text += `🎯 *Goal:* Save 45 mins daily cooking time during busy weekdays\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    text += `🌿 *1. SUNDAY NIGHT SOAKING & SPROUTING*\n`;
    if (hasRajma) text += `• Soak Rajma (Kidney Beans) in warm water with a pinch of salt (8-10 hrs)\n`;
    if (hasChana) text += `• Soak Kabuli Chana / Kala Chana for Monday & Wednesday curry (8 hrs)\n`;
    if (hasMoong) text += `• Soak Green Whole Moong for 6 hrs, drain and tie in muslin cloth for fresh sprouts\n`;
    text += `\n`;

    text += `🔪 *2. THE 30-MINUTE ALL-PURPOSE GRAVY BASE*\n`;
    text += `• Sauté 500g pureed onions + 500g tomatoes + ginger-garlic-chili paste in cold-pressed mustard/olive oil with turmeric and coriander.\n`;
    text += `• Divide into 3 glass containers in fridge. Use directly for 5-minute lunch & dinner gravies.\n\n`;

    text += `🥣 *3. BREAKFAST PRE-MIX & JARS*\n`;
    if (hasBesan) text += `• Dry mix Besan with ajwain, turmeric, hing, and salt in a dry jar. Just add water in the morning for instant chillas.\n`;
    if (hasOats) text += `• Pre-portion overnight rolled oats + chia seeds + cinnamon in 3 mason jars.\n`;
    text += `\n`;

    text += `🧊 *4. STORAGE & SHELF LIFE (ICMR Best Practice)*\n`;
    text += `• Boiled Pulses: 3-4 days in airtight glass container\n`;
    text += `• Homemade Ginger-Garlic Paste: 7 days (add 1/2 tsp oil + salt to prevent darkening)\n`;
    text += `• Fresh Dahi / Curd: Keep in terracotta or glass on middle shelf\n\n`;
    text += `_Generated by DietPlan AI_`;
    return text;
  };

  const handleShareWhatsApp = () => {
    const text = generatePrepText();
    const encoded = encodeURIComponent(text);
    window.open(`https://api.whatsapp.com/send?text=${encoded}`, '_blank');
  };

  const handleCopyText = () => {
    const text = generatePrepText();
    navigator.clipboard.writeText(text);
    setCopyToast(true);
    setTimeout(() => setCopyToast(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="bg-white rounded-3xl max-w-3xl w-full shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[92vh]"
      >
        {/* Header */}
        <div className="bg-gradient-to-r from-emerald-800 to-teal-900 text-white p-5 sm:p-6 flex items-center justify-between shrink-0">
          <div className="flex items-center space-x-3">
            <div className="w-11 h-11 rounded-2xl bg-emerald-400 text-slate-950 flex items-center justify-center font-black shadow-md shrink-0">
              <ChefHat className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-300">
                  Weekly Kitchen Accelerator
                </span>
                <span className="bg-emerald-500/30 text-emerald-100 text-[10px] px-2 py-0.5 rounded-full font-bold border border-emerald-400/30">
                  Save ~45m Daily
                </span>
              </div>
              <h2 className="text-xl sm:text-2xl font-black text-white">
                Sunday Meal Prep & Batch Guide
              </h2>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-white/10 hover:bg-white/20 text-white transition-colors cursor-pointer"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-6 text-xs sm:text-sm">
          
          {/* Introductory callout */}
          <div className="bg-emerald-50/80 border border-emerald-200/80 rounded-2xl p-4 flex items-start space-x-3">
            <Sparkles className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
            <div>
              <p className="font-bold text-slate-900 text-xs sm:text-sm">
                Customized for {userProfile?.name ? `${userProfile.name}'s Plan` : 'Your 7-Day Plan'} ({plan?.targetProteinGrams || 70}g Protein Target)
              </p>
              <p className="text-slate-600 text-xs mt-0.5 leading-relaxed">
                By investing 45 minutes on Sunday evening and 15 minutes mid-week, your high-protein vegetarian meals will be ready in under 12 minutes every day.
              </p>
            </div>
          </div>

          {/* 1. Soaking & Sprouting Matrix */}
          <div className="bg-white border border-slate-200 rounded-2xl p-4 sm:p-5 space-y-3 shadow-2xs">
            <div className="flex items-center justify-between border-b pb-2 border-slate-100">
              <h3 className="font-black text-slate-900 flex items-center space-x-2 text-sm">
                <span className="w-6 h-6 rounded-lg bg-emerald-100 text-emerald-800 flex items-center justify-center font-bold text-xs">1</span>
                <span>Sunday Night Soaking & Sprouting</span>
              </h3>
              <span className="text-[11px] text-slate-400 font-semibold">Anti-Bloating Essential</span>
            </div>

            <div className="space-y-2.5">
              {[
                {
                  id: 'soak_rajma',
                  title: 'Rajma / Kidney Beans Soaking',
                  desc: 'Soak in warm water with a pinch of rock salt for 8-10 hours. Discard soak water to remove phytates.',
                  active: hasRajma,
                  time: '10 hrs soak',
                },
                {
                  id: 'soak_chana',
                  title: 'Kabuli Chana / Kala Chana (Chickpeas)',
                  desc: 'Soak with 1 bay leaf and small piece of amla/dry ginger for optimal digestibility.',
                  active: hasChana,
                  time: '8 hrs soak',
                },
                {
                  id: 'sprout_moong',
                  title: 'Green Moong Sprouting',
                  desc: 'Soak for 6 hours, rinse, and hang in a moist cotton/muslin cloth. Increases Vitamin C and bioavailable protein by 22%.',
                  active: hasMoong,
                  time: '24-36 hrs sprout',
                },
              ].map((item) => (
                <div
                  key={item.id}
                  onClick={() => toggleTask(item.id)}
                  className={`p-3.5 rounded-xl border flex items-start space-x-3 transition-all cursor-pointer ${
                    checkedTasks[item.id]
                      ? 'bg-slate-50 border-slate-200 opacity-60'
                      : 'bg-emerald-50/40 border-emerald-200/80 hover:bg-emerald-50/80'
                  }`}
                >
                  <div className={`w-5 h-5 rounded-md flex items-center justify-center border mt-0.5 shrink-0 ${
                    checkedTasks[item.id] ? 'bg-emerald-600 border-emerald-600 text-white' : 'border-slate-300 bg-white'
                  }`}>
                    {checkedTasks[item.id] && <Check className="w-3.5 h-3.5 stroke-[3]" />}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <span className={`font-bold text-slate-900 ${checkedTasks[item.id] ? 'line-through text-slate-500' : ''}`}>
                        {item.title}
                      </span>
                      <span className="text-[10px] font-bold text-emerald-800 bg-emerald-100 px-2 py-0.5 rounded-full">
                        {item.time}
                      </span>
                    </div>
                    <p className="text-xs text-slate-600 mt-1">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* 2. The Universal 30-Minute Curry Base */}
          <div className="bg-white border border-slate-200 rounded-2xl p-4 sm:p-5 space-y-3 shadow-2xs">
            <div className="flex items-center justify-between border-b pb-2 border-slate-100">
              <h3 className="font-black text-slate-900 flex items-center space-x-2 text-sm">
                <span className="w-6 h-6 rounded-lg bg-amber-100 text-amber-800 flex items-center justify-center font-bold text-xs">2</span>
                <span>Universal Bhuna Masala & Gravy Base</span>
              </h3>
              <span className="text-[11px] text-amber-800 font-bold bg-amber-50 border border-amber-200 px-2 py-0.5 rounded-full">
                Saves 25m Per Meal
              </span>
            </div>

            <div className="bg-slate-50 p-3.5 rounded-xl border border-slate-200 text-xs space-y-2 text-slate-700 leading-relaxed">
              <p className="font-semibold text-slate-900">
                🍳 Batch Recipe (Yields 6-8 Meal Gravies):
              </p>
              <ul className="list-disc list-inside space-y-1 text-slate-600 pl-1">
                <li>Heat 3 tbsp mustard/olive oil with cumin, hing (asafoetida), and tej patta.</li>
                <li>Add 4 finely chopped onions + 2 tbsp fresh ginger-garlic-green chili paste; sauté till golden.</li>
                <li>Add pureed ripe tomatoes (400g), turmeric, coriander powder, Kashmiri chili, and cook until oil separates.</li>
                <li>Cool and store in 3 clean glass jars. Add 2 tbsp of this base directly to boiled chana, paneer, or dal for instant fresh meals!</li>
              </ul>
            </div>
          </div>

          {/* 3. Breakfast Pre-Mix & Jars */}
          <div className="bg-white border border-slate-200 rounded-2xl p-4 sm:p-5 space-y-3 shadow-2xs">
            <div className="flex items-center justify-between border-b pb-2 border-slate-100">
              <h3 className="font-black text-slate-900 flex items-center space-x-2 text-sm">
                <span className="w-6 h-6 rounded-lg bg-sky-100 text-sky-800 flex items-center justify-center font-bold text-xs">3</span>
                <span>10-Minute Morning Breakfast Shortcuts</span>
              </h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="p-3 bg-sky-50/60 border border-sky-200/80 rounded-xl space-y-1">
                <span className="text-[11px] font-bold text-sky-950 block">🥞 Besan & Sattu Chilla Dry Mix</span>
                <p className="text-xs text-slate-600">
                  Combine 2 cups besan, 1 cup sattu, 1 tsp ajwain, salt & turmeric in a dry container. In the morning, whisk with water and chopped coriander for 5-minute chillas.
                </p>
              </div>

              <div className="p-3 bg-amber-50/60 border border-amber-200/80 rounded-xl space-y-1">
                <span className="text-[11px] font-bold text-amber-950 block">🥣 Overnight High-Protein Oats</span>
                <p className="text-xs text-slate-600">
                  Pre-fill 3 mason jars with 40g rolled oats, 1 tbsp chia seeds, 1 tbsp pumpkin seeds, and cinnamon. Pour cold milk/soy milk the night before.
                </p>
              </div>
            </div>
          </div>

          {/* 4. ICMR Refrigeration & Food Safety Matrix */}
          <div className="bg-slate-900 text-white rounded-2xl p-4 sm:p-5 space-y-3">
            <h3 className="font-black text-emerald-300 flex items-center space-x-2 text-sm">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>ICMR 2024 Food Safety & Shelf-Life Guidelines</span>
            </h3>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
              <div className="bg-slate-800/80 p-2.5 rounded-xl border border-slate-700">
                <span className="text-slate-400 block text-[10px] uppercase font-bold">Boiled Dals</span>
                <span className="font-bold text-emerald-300">3 - 4 Days</span>
                <span className="text-[10px] text-slate-400 block mt-0.5">Airtight Glass</span>
              </div>

              <div className="bg-slate-800/80 p-2.5 rounded-xl border border-slate-700">
                <span className="text-slate-400 block text-[10px] uppercase font-bold">Paneer / Tofu</span>
                <span className="font-bold text-emerald-300">4 - 5 Days</span>
                <span className="text-[10px] text-slate-400 block mt-0.5">Submerged in water</span>
              </div>

              <div className="bg-slate-800/80 p-2.5 rounded-xl border border-slate-700">
                <span className="text-slate-400 block text-[10px] uppercase font-bold">Fresh Sprouts</span>
                <span className="font-bold text-emerald-300">3 Days</span>
                <span className="text-[10px] text-slate-400 block mt-0.5">Paper towel lined</span>
              </div>

              <div className="bg-slate-800/80 p-2.5 rounded-xl border border-slate-700">
                <span className="text-slate-400 block text-[10px] uppercase font-bold">Chilla Batter</span>
                <span className="font-bold text-emerald-300">2 Days</span>
                <span className="text-[10px] text-slate-400 block mt-0.5">Ferments fast</span>
              </div>
            </div>
          </div>

        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex flex-wrap items-center justify-between gap-3 shrink-0">
          <div className="flex items-center space-x-2">
            <button
              onClick={handleShareWhatsApp}
              className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs px-4 py-2.5 rounded-xl flex items-center space-x-1.5 transition-colors cursor-pointer shadow-xs"
            >
              <Send className="w-3.5 h-3.5" />
              <span>Share Prep on WhatsApp</span>
            </button>

            <button
              onClick={handleCopyText}
              className="bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 font-bold text-xs px-4 py-2.5 rounded-xl flex items-center space-x-1.5 transition-colors cursor-pointer"
            >
              <Copy className="w-3.5 h-3.5 text-slate-500" />
              <span>{copyToast ? 'Copied!' : 'Copy Prep Guide'}</span>
            </button>
          </div>

          <button
            onClick={onClose}
            className="text-xs font-semibold text-slate-500 hover:text-slate-800"
          >
            Close Guide
          </button>
        </div>

      </motion.div>
    </div>
  );
};
